# Generated by Django 6.0.3 on 2026-03-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawling", "0004_alter_crawlrawdata_unique_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawlrawdata",
            name="unique_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, unique=True
            ),
        ),
    ]
